baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "https://jesse.tg" # the base hostname & protocol for your site.
email: "jesse@jesse.tg"

title: "Jesse Makes Things"
subtitle: "Mostly with code."
name: "Jesse TG"
description: "The personal blog of Jesse TG."
logo: "/assets/image/logo.svg"

minimal_mistakes_skin: "mint"
locale: "en-US"
paginate: 5 #articles per page
paginate_path: /blog/page:num #makes pagination working

repository: "JesseTG/JesseTG.github.io"
github_username: JesseTG
linkedin: https://www.linkedin.com/in/jessetg

author:
  name: "Jesse TG"
  avatar: "/assets/image/jesse.jpg"
  bio: |
    I'm a software engineer that specializes at the intersection of
    systems programming and usability.
  location: "Long Island, NY"
  links: &links
    - label: "E-Mail"
      icon: "fa fa-fw fa-envelope"
      url: "mailto:jesse@jesse.tg"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: &github "https://github.com/JesseTG"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: &linkedin "https://www.linkedin.com/in/jessetg"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: &twitter "https://twitter.com/JesseT_G"
    - label: Reddit
      icon: "fab fa-fw fa-reddit"
      url: &reddit "https://www.reddit.com/user/JesseTG"
    - label: StackExchange
      icon: "fab fa-fw fa-stack-exchange"
      url: &stackexchange "https://stackexchange.com/users/1096459/jessetg"
    - label: "Google+"
      icon: "fab fa-fw fa-google-plus-square"
      url: "https://goo.gl/jN4CT2"

sass:
    style: :compressed

timezone: America/New_York
future: false

plugins:
  - jekyll-archives
  - jekyll-compose
  - jekyll-feed
  - jekyll-include-cache 
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - ".gitignore"
  - "LICENSE"
  - "CNAME"
  - ".idea"
  - "Justfile"
include:
  - "keybase.txt"

permalink: :title

defaults:
  - scope:
      path: ""
    values:
      author_profile: true
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true
      comments: true
      share: true
      related: true
  # _projects
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: archive
      author_profile: true
      show_date: false
      share: true
      related: true
      comments: true
      header:
        teaser: assets/image/default-teaser.jpg

collections:
  posts:
    output: true
    permalink: /blog/:title
  oldprojects:
    output: true
    permalink: /:collection/:title
  projects:
    output: true
    permalink: /:collection/:title

twitter:
  username: JesseT_G

social:
  links:
    - *github
    - *twitter
    - *linkedin
    - *reddit
    - *stackexchange

footer:
  links: *links

enable_copy_code_button: true
kramdown:
  gfm_emojis: true