baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "JesseTG.github.io" # the base hostname & protocol for your site.
title: "Jesse Makes Things"

minimal_mistakes_skin: "mint"
locale: "en-US"
paginate: 5 #articles per page
paginate_path: /blog/page:num #makes pagination working

repository: "JesseTG/JesseTG.github.io"
github_username: JesseTG

#contacts
github: "https://github.com/JesseTG"
stackexchange: "https://stackexchange.com/users/1096459/jessetg"
twitter: "https://twitter.com/JesseT_G"
linkedin: "https://www.linkedin.com/in/jessetg"
youtube: "https://www.youtube.com/channel/UCuvu5_FrOhwzmpX_nOGrsOg"
bitbucket: "https://bitbucket.org/jessetg/"
reddit: "https://www.reddit.com/user/JesseTG"
email: "jessetalavera@aol.com"

sass:
    style: :compressed

timezone: America/New_York
future: false

plugins:
  - jekyll-archives
  - jekyll-compose
  - jekyll-feed
  - jekyll-include-cache 
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
description: The personal blog of Jesse Talavera-Greenberg.

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - ".gitignore"
  - "LICENSE"
  - "CNAME"
include:
  - "keybase.txt"

permalink: :title

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

collections:
  art:
    output: true
    permalink: /:collection/:title
  projects:
    output: true
    permalink: /:collection/:title

# If any of these strings appear in a page, don't minify it
dont-minify:
  - '<pre'
  - '<code'
