baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "JesseTG.github.io" # the base hostname & protocol for your site.
title: "Jesse Makes Things"


paginate: 5 #articles per page
paginate_path: /blog/page:num #makes pagination working


#contacts
github: "https://github.com/JesseTG"
stackexchange: "https://stackexchange.com/users/1096459/jessetg"
twitter: "https://twitter.com/JesseT_G"
linkedin: "https://www.linkedin.com/in/jessetg"
youtube: "https://www.youtube.com/channel/UCuvu5_FrOhwzmpX_nOGrsOg"
bitbucket: "https://bitbucket.org/jessetg/"
reddit: "https://www.reddit.com/user/JesseTG"

sass:
    style: :compressed

timezone: America/New_York
future: false

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
  - jemoji

description: The personal blog of Jesse Talavera-Greenberg.

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "jessetg.sublime-project"
  - ".gitignore"
  - "LICENSE"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

collections:
  art:
    output: true
    permalink: /:collection/:title
  projects:
    output: true
    permalink: /:collection/:title

# If any of these strings appear in a page, don't minify it
dont-minify:
  - '<pre'
  - '<code'