baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "JesseTG.github.io" # the base hostname & protocol for your site.
email: jesse@jesse.tg
title: "Jesse Makes Things"

minimal_mistakes_skin: "mint"
locale: "en-US"
paginate: 5 #articles per page
paginate_path: /blog/page:num #makes pagination working

repository: "JesseTG/JesseTG.github.io"
github_username: JesseTG
twitter: JesseT_G

author:
  name: "Jesse TG"
  avatar: "/assets/image/jesse.jpg"
  bio: "My awesome biography constrained to a sentence or two goes here."
  links:
    - label: "E-Mail"
      icon: "fa fa-fw fa-envelope"
      url: "mailto:jesse@jesse.tg"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JesseTG"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jessetg"
    - label: YouTube
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCuvu5_FrOhwzmpX_nOGrsOg"
    - label: Reddit
      icon: "fab fa-fw fa-reddit"
      url: "https://www.reddit.com/user/JesseTG"
    - label: StackExchange
      icon: "fab fa-fw fa-stack-exchange"
      url: "https://stackexchange.com/users/1096459/jessetg"
    - label: "Google+"
      icon: "fab fa-fw fa-google-plus-square"
      url: "https://goo.gl/jN4CT2"

sass:
    style: :compressed

timezone: America/New_York
future: false

plugins:
  - jekyll-archives
  - jekyll-compose
  - jekyll-feed
  - jekyll-include-cache 
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
description: The personal blog of Jesse Talavera-Greenberg.

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - ".gitignore"
  - "LICENSE"
  - "CNAME"
include:
  - "keybase.txt"

permalink: :title

defaults:
  - scope:
      path: ""
    values:
      author_profile: true
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: single
      author_profile: true
      share: true
      related: true
      comments: true

collections:
  art:
    output: true
    permalink: /:collection/:title
  projects:
    output: true
    permalink: /:collection/:title
