baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "JesseTG.github.io" # the base hostname & protocol for your site.
title: "Jesse Makes Things"


paginate: 5 #articles per page
paginate_path: /blog/page:num #makes pagination working


#contacts
git: "https://github.com/JesseTG"  #Add your github url here.
stackoverflow: "http://stackoverflow.com/users/1089957/jessetg" #Add your stackoverflow url here.
twitter: "https://twitter.com/JesseT_G"  #Add your twitter url here.
linkedin: "https://www.linkedin.com/profile/view?id=204321371"

sass:
    style: :compressed

gems:
  - jekyll-sitemap

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
